// Tests für „Umstellen“ (8r): core-observe.js, abgestufter Tacho (core-index.js), Tagebuch-Kennzeichen (core-benchmark.js)
import { OBS, obsFresh, obsKey, obsResult, obsText, timeExitDue, timeExitText, biasSide, biasTurn, biasTurnText } from './core-observe.js';
import { tachoFrom, aboveFast } from './core-index.js';
import { engineOf, splitByEngine, journalWindow, bmHoldDays } from './core-benchmark.js';
import { journalEntry, publicSignals } from './core-alerts.js';

const DAY = 864e5, NOW = Date.UTC(2026, 9, 8, 12);
const E = (finds, extra = {}) => ({ coin: 'JTO', price: 0.52, R: 0.05, n: finds.length, finds: finds.map(([rule, ago]) => ({ rule, ago })), rooms: [{ tf: 'Woche', state: 'frei' }, { tf: 'Tag', state: 'weg', r: 1.2 }, { tf: '4H', state: 'weg', r: 0.4 }], ...extra });
const B = { btcUp: true, altUp: true, btcAbove: true, altAbove: false, breadth: 2, room: [] };
const line = (n, f) => { const out = []; let p = 100; for (let k = 0; k < n; k++) { const c = p * f; out.push({ t: k * DAY, T: (k + 1) * DAY - 1, o: p, h: Math.max(p, c), l: Math.min(p, c), c }); p = c; } return out; };

export const tests = [
  ['Beobachtung: nur mit frischem Baustein auf der letzten 4H-Kerze und ab 2 Bausteinen', () => obsFresh(E([['r6', 0], ['r4', 3]])) && !obsFresh(E([['r6', 1], ['r4', 3]])) && !obsFresh(E([['r6', 0]])) && !obsFresh(null) && OBS.minBlocks === 2],
  ['Beobachtung: eindeutiger Schlüssel je Coin und Kerze', () => obsKey('JTO', 5) === 'obs|JTO|5' && obsKey('JTO', 5) !== obsKey('JTO', 6)],
  ['Beobachtung: Rahmen-Plan (2 × Tages-ATR) und Bausteine als Ereignisse fürs Tagebuch', () => { const r = obsResult(E([['r6', 0], ['r4', 3]]), 0.5); return r.plan.entry === 0.5 && Math.abs(r.plan.stop - 0.45) < 1e-12 && r.events.map((x) => x.name).join() === 'Order Block,Sweep' && r.events.every((x) => x.dir === 'long'); }],
  ['Beobachtung: Tagebuch-Eintrag mit Bausteinen, ohne Score; öffentlich nur unbedenkliche Felder', () => { const r = obsResult(E([['r6', 0], ['r4', 3]])); const j = { ...journalEntry(r, { score: null, pos: { state: 'zone' }, price: r.plan.entry }, NOW, null), eng: 'obs', blocks: ['r6', 'r4'] }; const p = publicSignals([j])[0]; return j.score === null && j.events.join() === 'Order Block,Sweep' && j.status === 'offen' && p.events.length === 2 && !('blocks' in p); }],
  ['Beobachtung: Telegram-Text heißt „Beobachtung“, nennt Bausteine, Markt, Rahmen-Stop, Zeit-Ausstieg, und behauptet keinen Vorteil', () => { const e = E([['r6', 0], ['r4', 3]]), t = obsText(e, obsResult(e), { bias: B, id: 7, appUrl: 'https://x' }); return /Beobachtung/.test(t) && /#WD-0007/.test(t) && /2 Bausteine: Order Block, Sweep/.test(t) && /Markt · BTC aufwärts · Alts aufwärts/.test(t) && /Rahmen-Stop/.test(t) && /Zeit-Ausstieg im Rahmen nach 10 Tagen/.test(t) && /kein geprüftes Signal/.test(t) && !/Score|Treffer/.test(t) && /Platz nach oben/.test(t); }],
  ['Zeit-Ausstieg: erst nach 10 Tagen, einmal je Trade, nicht für Trades mit unvollständiger Historie', () => { const pos = [{ coin: 'JTO', side: 'long' }, { coin: 'SOL', side: 'long' }, { coin: 'ETH', side: 'long' }]; const tr = [{ coin: 'JTO', openedAt: NOW - 10.5 * DAY, closedAt: null }, { coin: 'SOL', openedAt: NOW - 3 * DAY, closedAt: null }, { coin: 'ETH', openedAt: NOW - 20 * DAY, closedAt: null, partial: true }]; const a = timeExitDue(pos, tr, {}, NOW), b = timeExitDue(pos, tr, { [a[0].key]: 1 }, NOW); return a.length === 1 && a[0].coin === 'JTO' && a[0].days === 10 && b.length === 0; }],
  ['Zeit-Ausstieg: Text mit Coin, Tagen und Einstieg', () => /JTO<\/b> Long läuft seit 10 Tagen \(Einstieg 28\.09\.\)/.test(timeExitText({ coin: 'JTO', side: 'long', openedAt: Date.UTC(2026, 8, 28, 10), days: 10 }))],
  ['Bias-Wechsel: nur zwischen bullisch, gemischt und bärisch; erster Lauf meldet nichts', () => biasSide({ value: 60 }) === 'bullisch' && biasSide({ value: 0 }) === 'gemischt' && biasSide({ value: -20 }) === 'bärisch' && biasSide(null) === null && biasTurn(null, { value: 60 }) === null && biasTurn('bullisch', { value: 80 }) === null && biasTurn('bullisch', { value: 0 }).to === 'gemischt'],
  ['Bias-Wechsel: Text nennt offene Positionen und warnt, wenn eine gegen den Markt steht', () => { const t = biasTurnText({ from: 'bullisch', to: 'bärisch' }, { label: 'Leicht bärisch', value: -40 }, null, [{ coin: 'JTO', side: 'long' }]); return /dreht: bullisch → bärisch/.test(t) && /JTO Long/.test(t) && /gegen den Markt/.test(t) && !/gegen den Markt/.test(biasTurnText({ from: 'gemischt', to: 'bullisch' }, { label: 'Long-Markt', value: 100 }, null, [{ coin: 'JTO', side: 'long' }])); }],
  ['Tacho abgestuft: Rücksetzer im Aufwärtstrend zählt halb (Kurs unter EMA 20)', () => { const a = tachoFrom({ btcUp: true, altUp: true, btcAbove: true, altAbove: true, breadth: 2 }), b = tachoFrom(B), c = tachoFrom({ btcUp: true, altUp: true, btcAbove: false, altAbove: false, breadth: -2 }); return a.value === 100 && b.value === 80 && b.parts.altPull === true && b.parts.btcPull === false && c.value === 20 && c.label === 'Leicht bullisch'; }],
  ['Tacho abgestuft: Erholung im Abwärtstrend zählt halb, ohne EMA-Angabe wie bisher', () => tachoFrom({ btcUp: false, altUp: false, btcAbove: true, altAbove: false, breadth: 0 }).value === -60 && tachoFrom({ btcUp: true, altUp: true, breadth: 0 }).value === 80],
  ['Über der EMA 20: letzter Tagesschluss gegen EMA 20', () => aboveFast(line(40, 1.01)) === true && aboveFast(line(40, 0.99)) === false && aboveFast(line(5, 1.01)) === null],
  ['Tagebuch: Beobachtungen eigene Gruppe in der Auswertung, Fenster 10 Tage wie im Rahmen', () => engineOf({ eng: 'obs' }) === 'obs' && engineOf({ eng: 'bm' }) === 'bm' && engineOf({}) === 'alt' && splitByEngine([{ eng: 'obs' }, { eng: 'bm' }, {}]).obs.length === 1 && journalWindow({ eng: 'obs' }) === bmHoldDays()],
];
