// Tests für den Hyperliquid-Ledger-Perp-Index und den Markt-Bias (8m): core-index.js
import { IDX, buildIndex, extendSeries, extendIndex, trendOf, perfPct, relStrength, marketRoom, marketBias, breadthText, marketRoomText, biasLines, coinBiasText, capExBtcText, packIndex, unpackIndex, loadIndex, saveIndex, needsRebuild } from './core-index.js';

const DAY = 864e5, T0 = Date.UTC(2024, 0, 1), near = (a, b, eps = 1e-9) => a != null && b != null && Math.abs(a - b) < eps;
// Markt mit festem Tagesfaktor: Eröffnung = Schluss vom Vortag, Hoch und Tief 1 % darüber und darunter
const mk = (days, f, { start = 0, p0 = 10, vol = 100 } = {}) => { const out = []; let p = p0; for (let k = 0; k < days; k++) { const o = p, c = o * (typeof f === 'function' ? f(k) : f); out.push({ t: T0 + (start + k) * DAY, T: T0 + (start + k + 1) * DAY - 1, o, c, h: Math.max(o, c) * 1.01, l: Math.min(o, c) * 0.99, v: vol / c }); p = c; } return out; };
const CFG = { ...IDX, minDays: 3, top: 2, volDays: 2, minMembers: 2 };
// Sechs Alts: A und B groß (hoher Umsatz) und steigend, C bis F klein und fallend; dazu BTC
const SER = { BTC: mk(12, 1.5), A: mk(12, 1.02, { vol: 9000 }), B: mk(12, 1.02, { vol: 8000 }), C: mk(12, 0.99), D: mk(12, 0.99), E: mk(12, 0.99), F: mk(12, 0.99) };
const X = buildIndex(SER, CFG);
const flat = (n, c = 100) => Array.from({ length: n }, (_, k) => ({ t: T0 + k * DAY, T: T0 + (k + 1) * DAY - 1, o: c, h: c, l: c, c }));
const line = (n, f) => { const out = []; let p = 100; for (let k = 0; k < n; k++) { const o = p, c = p * f; out.push({ t: T0 + k * DAY, T: T0 + (k + 1) * DAY - 1, o, c, h: Math.max(o, c), l: Math.min(o, c) }); p = c; } return out; };
const mem = () => { const m = new Map(); return { getItem: (k) => (m.has(k) ? m.get(k) : null), setItem: (k, v) => m.set(k, v) }; };
// Index mit einem Sell-Block über dem Kurs (Bau wie im Sell-Block-Test: Swing-Tief, steigende Kerze, Bruch)
const cs = (rows) => rows.map(([o, h, l, c], k) => ({ t: T0 + k * DAY, T: T0 + (k + 1) * DAY - 1, o, h, l, c }));
const F = [100, 100.5, 99.5, 100], BLK = cs([...Array(6).fill(F), [100, 100.5, 95, 100], ...Array(5).fill(F), [100, 102, 99.8, 101.5], [101.5, 101.6, 93, 94]]);

export const tests = [
  ['Index: BTC zählt nicht mit, jeder Alt zählt gleich viel (Mittel der Tagesänderungen)', () => { const a = X.alt[0]; return a.n === 6 && near(a.c, 100 * (2 * 1.02 + 4 * 0.99) / 6) && near(a.o, 100); }],
  ['Index: ein Markt zählt erst nach der Wartezeit mit (hier 3 Tage, in der App 110)', () => X.alt[0].t === T0 + 3 * DAY && X.alt.length === 9 && IDX.minDays === 110],
  ['Index: ein neu gelisteter Markt lässt den Index nicht springen und kommt erst nach der Wartezeit dazu', () => { const s = { ...SER, NEU: mk(6, 3, { start: 6 }) }; const y = buildIndex(s, CFG); return y.alt[5].n === 6 && near(y.alt[5].c, X.alt[5].c) && y.alt[6].n === 7 && y.alt[6].t === T0 + 9 * DAY; }],
  ['Index: Kette aus Tagesänderungen, Start bei 100', () => near(X.alt[1].c, X.alt[0].c * (2 * 1.02 + 4 * 0.99) / 6) && near(X.alt[1].o, X.alt[0].c)],
  ['Index: Hoch und Tief umschließen Eröffnung und Schluss', () => [...X.alt, ...X.small].every((c) => c.h >= Math.max(c.o, c.c) && c.l <= Math.min(c.o, c.c))],
  ['Small-Index: ohne die umsatzstärksten (hier 2, in der App 10)', () => X.small[0].n === 4 && near(X.small[0].c, 99) && IDX.top === 10],
  ['Small-Index: die Rangliste nutzt nur den Umsatz der Tage davor (kein Blick in die Zukunft)', () => { const s = { ...SER, C: SER.C.map((c, k) => (k === 11 ? { ...c, v: 1e9 } : c)) }; const y = buildIndex(s, CFG); return near(y.small.at(-1).c, X.small.at(-1).c); }],
  ['Small-Index: Umsatz zählt in USD (Stück × Kurs), nicht in Stück', () => { const s = { A: mk(8, 1.02, { vol: 9000, p0: 5000 }), B: mk(8, 1.02, { vol: 8000, p0: 1 }), C: mk(8, 0.99, { p0: 0.01 }), D: mk(8, 0.99), E: mk(8, 0.99) }; const y = buildIndex(s, { ...CFG, top: 1, minMembers: 2 }); return y.small[0].n === 4 && y.small[0].c > 99 && y.small[0].c < 100; }],
  ['Index: zu wenig Mitglieder an einem Tag heißt kein Wert', () => buildIndex({ A: SER.A }, CFG).alt.length === 0 && buildIndex({}, CFG).alt.length === 0 && buildIndex(null, CFG).small.length === 0],
  ['Index: nach einer Lücke in den Kerzen zählt der Markt an dem Tag nicht mit', () => { const gap = SER.C.filter((_, k) => k !== 7); const y = buildIndex({ ...SER, C: gap }, CFG); return y.alt.find((c) => c.t === T0 + 8 * DAY).n === 5 && y.alt.find((c) => c.t === T0 + 6 * DAY).n === 6; }],
  ['Fortschreiben: neue Tage werden an den gespeicherten Index angekettet, ohne Sprung', () => { const stored = X.alt.slice(0, 5).map((c) => ({ ...c, o: c.o * 3, h: c.h * 3, l: c.l * 3, c: c.c * 3 })), out = extendSeries(stored, X.alt.slice(3)); return out.length === 9 && near(out[4].c, stored[4].c) && near(out[5].c / out[4].c, X.alt[5].c / X.alt[4].c) && near(out[8].c, X.alt[8].c * 3); }],
  ['Fortschreiben: ohne gemeinsamen Tag geht es nicht (dann wird neu aufgebaut)', () => extendSeries(X.alt.slice(0, 3), X.alt.slice(5)) === null && extendIndex({ alt: X.alt.slice(0, 3), small: X.small.slice(0, 3) }, { alt: X.alt.slice(5), small: X.small.slice(5) }) === null],
  ['Fortschreiben: nichts Neues heißt unverändert; leerer Speicher nimmt den frischen Index', () => extendSeries(X.alt, X.alt.slice(2)).length === 9 && extendSeries(null, X.alt).length === 9 && extendSeries([], []) === null && extendIndex(X, X).alt.length === 9],
  ['Trend: Tages-EMA 20 über EMA 100, erst ab 110 Tagen', () => trendOf(line(150, 1.01)) === true && trendOf(line(150, 0.99)) === false && trendOf(line(100, 1.01)) === null && trendOf(null) === null],
  ['Veränderung über 30 Tage in Prozent', () => near(perfPct(line(40, 1.01)), (Math.pow(1.01, 30) - 1) * 100, 1e-6) && perfPct(line(30, 1.01)) === null],
  ['Stärke: Unterschied in Prozentpunkten', () => near(relStrength(line(40, 1.01), line(40, 1)), (Math.pow(1.01, 30) - 1) * 100, 1e-6) && relStrength(line(40, 1.01), null) === null],
  ['Platz nach oben (Markt): Abstand bis zum Sell-Block in Prozent, Woche und Tag getrennt', () => { const r = marketRoom(BLK); const d = r.find((x) => x.tf === 'Tag'); return r.map((x) => x.tf).join() === 'Woche,Tag' && d.state === 'weg' && near(d.pct, (100 / 94 - 1) * 100) && r[0].state === 'frei'; }],
  ['Platz nach oben (Markt): Index im Block wird gesagt; ohne Block frei', () => { const inB = marketRoom([...BLK, ...cs([[94, 101, 94, 101]]).map((c) => ({ ...c, t: T0 + 14 * DAY }))]).find((x) => x.tf === 'Tag'); return inB.state === 'im' && marketRoom(flat(30)).every((x) => x.state === 'frei') && marketRoom([]).length === 0; }],
  ['Markt-Bias: drei Ebenen (BTC-Trend, Alt-Trend, Small gegen Alt) und Platz nach oben', () => { const b = marketBias(line(150, 1.01), { alt: line(150, 0.99), small: line(150, 0.98) }); return b.btcUp === true && b.altUp === false && b.breadth < -1 && b.room.length === 2 && b.from === T0; }],
  ['Markt-Bias: kein Score und keine Ampelzahl', () => { const b = marketBias(line(150, 1.01), { alt: line(150, 1.01), small: line(150, 1.01) }); return !('score' in b) && !('value' in b) && typeof b.btcUp === 'boolean'; }],
  ['Kopfzeile: Text für Trend, Breite und Platz nach oben', () => { const L = biasLines({ btcUp: true, altUp: false, breadth: -3.24, room: [{ tf: 'Woche', state: 'frei', pct: null }, { tf: 'Tag', state: 'weg', pct: 4.26 }] }); return L[0] === 'Markt · BTC aufwärts · Alts nicht aufwärts' && L[1] === 'Small Caps schwächer als die Alts (−3,2 Prozentpunkte in 30 Tagen)' && L[2] === 'Platz nach oben (Alts) · Woche: frei · Tag: 4,3 %'; }],
  ['Kopfzeile: gleichauf innerhalb eines Prozentpunkts; zu wenig Historie wird gesagt', () => breadthText(0.4) === 'Small Caps gleichauf mit den Alts (30 Tage)' && /stärker.*\+2,0/.test(breadthText(2)) && breadthText(null) === '' && biasLines({ btcUp: null, altUp: null, breadth: null, room: [] })[0] === 'Markt · BTC: zu wenig Historie · Alts: zu wenig Historie' && biasLines(null).length === 0],
  ['Kopfzeile: Platz nach oben frei und im Block', () => /frei, kein Sell-Block/.test(marketRoomText([{ tf: 'Woche', state: 'frei' }, { tf: 'Tag', state: 'frei' }])) && /Tag: Index im Sell-Block/.test(marketRoomText([{ tf: 'Woche', state: 'frei' }, { tf: 'Tag', state: 'im', pct: 0 }])) && marketRoomText([]) === ''],
  ['Coin-Bias: Tagestrend und Stärke gegen BTC', () => coinBiasText(true, 12.34) === 'Tagestrend aufwärts · stärker als BTC (+12,3 Prozentpunkte in 30 Tagen)' && coinBiasText(true, -5) === 'Tagestrend aufwärts · schwächer als BTC (−5,0 Prozentpunkte in 30 Tagen)' && coinBiasText(true, 0.2) === 'Tagestrend aufwärts · gleichauf mit BTC (30 Tage)' && coinBiasText(true, null) === 'Tagestrend aufwärts' && coinBiasText(null, null) === ''],
  ['Zusatzzeile CoinGecko: Marktkap. ohne BTC aus Gesamtwert und Dominanz', () => capExBtcText({ cap: 3e12, btcDom: 60 }) === 'Marktkap. ohne BTC: 1,20 Bio. $ (CoinGecko, Stand jetzt · BTC-Dominanz 60,0 %)' && /800 Mrd/.test(capExBtcText({ cap: 2e12, btcDom: 60 })) && capExBtcText(null) === '' && capExBtcText({ cap: 3e12 }) === ''],
  ['Speicher: Index übersteht Speichern und Laden', () => { const st = mem(); const ok = saveIndex(X, st), y = loadIndex(st); return ok && y.alt.length === 9 && y.small.length === 9 && y.alt[3].t === X.alt[3].t && near(y.alt[8].c, X.alt[8].c, 1e-3) && y.alt[0].n === 6 && y.alt[0].T === y.alt[0].t + DAY - 1; }],
  ['Speicher: leer, kaputt oder alte Fassung heißt kein Index', () => { const st = mem(); st.setItem('wolfdesk.hlindex', '{kaputt'); return loadIndex(mem()) === null && loadIndex(st) === null && unpackIndex({ v: 0, alt: [], small: [] }) === null && unpackIndex(packIndex(X)).alt.length === 9; }],
  ['Speicher: nur Marktdaten (Tag, vier Kurse, Zahl der Märkte), nichts vom Konto', () => { const p = packIndex(X); return Object.keys(p).join() === 'v,alt,small' && p.alt.every((r) => r.length === 6 && r.every((x) => typeof x === 'number')); }],
  ['Neu aufbauen: ohne Speicher oder nach mehr als 140 Tagen Lücke', () => needsRebuild(null) === true && needsRebuild(X, X.alt.at(-1).t + 10 * DAY) === false && needsRebuild(X, X.alt.at(-1).t + 141 * DAY) === true],
];
