// Tests für Testplan 2 „Marktphase“ (8s): core-tp2.js
import { TP2, SW_KEYS, period2, ranges2, switchBmsb, switchEma, switchBreadth, dayBefore, countPhases, evalSwitch, passA2, verdict2, agreement, synthMarket, probeVerdict, resultText2 } from './core-tp2.js';
import { prepare, LT } from './core-longtest.js';
import { pack } from './core-binance.js';

const DAY = 864e5, H4 = 4 * 36e5, ST = Date.UTC(2026, 9, 6), near = (a, b, e = 1e-9) => a != null && b != null && Math.abs(a - b) < e;
const days = (n, f, from = Date.UTC(2020, 0, 6)) => { const out = []; let p = 100; for (let k = 0; k < n; k++) { const c = typeof f === 'function' ? f(k, p) : p * f; out.push({ t: from + k * DAY, T: from + (k + 1) * DAY - 1, o: p, h: Math.max(p, c), l: Math.min(p, c), c, v: 1 }); p = c; } return out; };
// Einstiege von Hand: ein Durchgang je Eintrag-Liste; Tag k bekommt Ergebnis r
const R0 = Date.UTC(2021, 0, 1), dayT = (k) => R0 + k * DAY;
function mkE(list, draws = 1) { return { r: Float64Array.from(list.map((x) => x[1])), run: Int32Array.from(list.map((x) => x[2] || 0)), day: Float64Array.from(list.map((x) => dayT(x[0]))), up: Uint8Array.from(list.map(() => 1)), t: Float64Array.from(list.map((x) => dayT(x[0]) + DAY)), draws }; }
// Schalter, der 30 Tage an, 30 Tage aus wechselt, über 600 Tage
const SW = new Map(Array.from({ length: 600 }, (_, k) => [dayT(k), Math.floor(k / 30) % 2 === 0]));
const RNG = [dayT(0), dayT(600)];

export const tests = [
  ['Zeiträume: Sperrfrist 10 Tage vor der Grenze zur Prüfung und vor dem Tresor; Tresor gar nicht', () => { const R = ranges2(ST); return period2(R.dev[1] - 11 * DAY, ST) === 'dev' && period2(R.dev[1] - 5 * DAY, ST) === 'sperre' && period2(R.dev[1] + DAY, ST) === 'check' && period2(R.check[1] - 5 * DAY, ST) === 'sperre' && period2(R.check[1] + DAY, ST) === null && period2(Date.UTC(2019, 0, 1), ST) === null; }],
  ['Schalter 3: Tagesschluss über der Tages-EMA 100, erst ab 100 Tagen', () => { const up = switchEma(days(150, 1.01)), dn = switchEma(days(150, 0.99)); return up.size === 51 && [...up.values()].every(Boolean) && [...dn.values()].every((x) => !x); }],
  ['Schalter 1 (BMSB): über SMA 20 und EMA 21 der abgeschlossenen Wochen; im Aufwärtslauf an, im Abwärtslauf aus', () => { const up = switchBmsb(days(300, 1.005)), dn = switchBmsb(days(300, 0.995)); return up.size > 100 && [...up.values()].every(Boolean) && [...dn.values()].every((x) => !x); }],
  ['Schalter 1: nutzt nur abgeschlossene Wochen (ein Sprung am letzten Tag ändert die Linien nicht)', () => { const a = days(200, 1.001), b = a.map((x, k) => (k === 199 ? { ...x, c: x.c * 3, h: x.c * 3 } : x)); const ka = [...switchBmsb(a).keys()], last = ka.at(-2); return switchBmsb(a).get(last) === switchBmsb(b).get(last) && switchBmsb(b).get(a[199].t) === true; }],
  ['Schalter 2 (Breite): mehr als die Hälfte der Märkte mit 110 Tagen im Tagestrend aufwärts', () => { const s = switchBreadth({ A: days(150, 1.01), B: days(150, 1.01), C: days(150, 0.99) }), t = switchBreadth({ A: days(150, 1.01), C: days(150, 0.99) }); const k = days(150, 1)[140].t; return s.get(k) === true && t.get(k) === false && !s.has(days(150, 1)[100].t); }],
  ['Einteilung: Stand am letzten Tag, der VOR der Einstiegskerze abgeschlossen war', () => { const D = days(130, 1.001), G = []; for (let t = D[0].t; t < D.at(-1).t + DAY; t += H4) G.push({ t, o: 1, h: 1, l: 1, c: 1, v: 1 }); const M = prepare('X', D, pack(G)); const i = 6 * 120 + 5, j = 6 * 120; return dayBefore(M, i) === D[119].t && dayBefore(M, j) === D[119].t && dayBefore(M, 0) === null; }],
  ['Phasen: kurze Ausreißer unter 10 Tagen zählen nicht als Wechsel', () => { const S = [...Array(30).fill(true), ...Array(5).fill(false), ...Array(30).fill(true), ...Array(20).fill(false), ...Array(12).fill(true)]; const p = countPhases(S); return p.flips === 2 && p.rawFlips === 4 && p.long === 3; }],
  ['Phasen: gleichmäßiger Wechsel alle 30 Tage', () => { const p = countPhases([...SW.values()]); return p.flips === 19 && near(p.avgLen, 30); }],
  ['Auswertung: Differenz an minus aus, je Durchgang und gepoolt', () => { const r = evalSwitch(mkE([[5, 1, 0], [35, 0, 0], [65, 1, 1], [95, -1, 1]], 2), SW, RNG); return near(r.real, 1 - -0.5) && r.pctRuns === 100 && r.nOn === 1 && r.nOff === 1; }],
  ['Verschiebe-Test: alle Verschiebungen von 60 bis Länge minus 60, kein Würfel', () => { const r = evalSwitch(mkE(Array.from({ length: 600 }, (_, k) => [k, SW.get(dayT(k)) ? 1 : 0])), SW, RNG); return r.shifts === 600 - 120 + 1 && r.pctShift > 90 && passA2(r); }],
  ['Verschiebe-Test: ein Schalter ohne Bezug zu den Ergebnissen schlägt seine Kopien nicht', () => { const r = evalSwitch(mkE(Array.from({ length: 600 }, (_, k) => [k, Math.sin(k * 1.7)])), SW, RNG); return r.pctShift < 98 && !passA2(r); }],
  ['Auswertung: Einstiege ohne Schalterstand zählen nicht', () => { const r = evalSwitch(mkE([[5, 1], [700, 5]]), SW, RNG); return r.nOn === 1 && r.nOff === 0 && r.real === null; }],
  ['Urteil: Abbruch, wenn A in der Entwicklung fehlt; Prüfung nur nach bestandenem A', () => { const bad = { pctRuns: 99, pctShift: 50, avgOn: 0.1, nOff: 200, flips: 12, nOn: 400 }, good = { pctRuns: 99, pctShift: 99, avgOn: 0.1, nOff: 200, flips: 12, nOn: 200 }; const a = verdict2(bad, null), b = verdict2(good, null), c = verdict2(good, { ...good, flips: 6 }); return a.dropped && !a.canCheck && b.canCheck && !b.dropped && c.vault && !verdict2(good, { ...good, flips: 4 }).vault && !verdict2(good, { ...good, nOff: 50 }).vault; }],
  ['Urteil: A1 wird seit der Anpassung nach der Probe nur berichtet; als Bedingung zählt der Verschiebe-Test ab 98 %', () => TP2.a1 === null && TP2.pass === 98 && passA2({ pctRuns: 10, pctShift: 98 }) && !passA2({ pctRuns: 100, pctShift: 97 }) && !passA2({ pctRuns: 97, pctShift: 99 }, { ...TP2, a1: 98 })],
  ['Einigkeit zweier Schalter', () => near(agreement(SW, SW, RNG), 100) && near(agreement(SW, new Map([...SW].map(([k, v]) => [k, !v])), RNG), 0)],
  ['Proben: Zufallskurse ohne Drift, 4H-Kerzen und Tageskerzen passen zusammen', () => { const x = synthMarket(7, Date.UTC(2020, 0, 1), Date.UTC(2020, 3, 1)); return x.g.n === 91 * 6 && x.daily.length === 91 && x.daily[3].c === x.g.c[23] && x.daily.every((d) => d.h >= Math.max(d.o, d.c) && d.l <= Math.min(d.o, d.c)); }],
  ['Proben: Urteil (ohne Vorteil höchstens 3 von 50 je Schalter, mit Vorteil mindestens 40 von 50)', () => { const no = Array.from({ length: 50 }, (_, k) => ({ s1: k < 3, s2: false, s3: k < 4 })), ed = Array.from({ length: 50 }, (_, k) => k < 40); const v = probeVerdict(no, ed); return !v.ok && !v.okNo && v.okEdge && v.per.s3 === 4 && probeVerdict(no.map((x) => ({ ...x, s3: false })), ed).ok && !probeVerdict(no.map((x) => ({ ...x, s3: false })), ed.slice(1)).ok; }],
  ['Text fürs Protokoll nennt Proben, A/B/C und ob die Prüfung zu bleibt', () => { const d = { pctRuns: 99, pctShift: 40, avgOn: 0.1, avgOff: 0, real: 0.1, nOn: 400, nOff: 200, flips: 12, rawFlips: 30, draws: 200, shifts: 400, share: 55, days: 1400, years: {} }; const t = resultText2({ probe: { per: { s1: 0, s2: 1, s3: 0 }, sets: 50, edgePass: 45, edgeSets: 50, ok: true }, s1: { dev: d } }, '8s'); return /Proben bestanden/.test(t) && /ABGELEGT/.test(t) && /Verschiebe-Test: besser als 40 %/.test(t) && SW_KEYS.length === 3; }],
];
